---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OlegDokuka/spring-cloud-starter.git
          searchPaths: cloud-config-data
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001