server:
  context-path: /uaa
  use-forward-headers: true
  port: ${PORT:8762}

security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

logging:
  level:
    org.springframework.security: DEBUG

