server:
  context-path: /uaa

security:
  sessions: STATELESS
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

logging:
  level:
    org.springframework.security: DEBUG
