---
# Items that apply to ALL profiles:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
spring:
  server:
    port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: subject
  application:
    name: eureka-starter-subject
words: I,You,He,She,It
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: verb
  application:
    name: eureka-starter-verb
words: ran,knew,had,saw,bought
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: article
  application:
    name: eureka-starter-article
words: a,the
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: adjective
  application:
    name: eureka-starter-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: noun
  application:
    name: eureka-starter-noun
words: boat,book,vote,seat,backpack,partition,groundhog 
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} 

---
spring:
  profiles: subject-ru
  application:
    name: eureka-starter-subject
words: Я,Вы,Ты,Он,Она,Это
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: verb-ru
  application:
    name: eureka-starter-verb
words: бежал,знал,имел,видел,покупал
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: article-ru
  application:
    name: eureka-starter-article
words: какой-то,конкретный
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: adjective-ru
  application:
    name: eureka-starter-adjective
words: разумно,дырявое,подозрительный,обычный,маловероятно
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: noun-ru
  application:
    name: eureka-starter-noun
words: лодка,книга,голосование,место,рюкзак,перегородка,сурок 
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}